"""fix verification code field length and allow nullable email

Revision ID: af8897561ac5
Revises: f579960911db
Create Date: 2025-11-27 22:16:32.890507

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "af8897561ac5"
down_revision = "f579960911db"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "email",
        existing_type=sa.VARCHAR(length=255),
        nullable=True,
        comment="Email address (nullable for OAuth users without email)",
        existing_comment="Email address",
    )
    op.alter_column(
        "verification_codes",
        "code",
        existing_type=sa.VARCHAR(length=32),
        type_=sa.String(length=64),
        comment="Hashed verification code (SHA-256, 64 hex chars)",
        existing_comment="Verification code (should be hashed)",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "verification_codes",
        "code",
        existing_type=sa.String(length=64),
        type_=sa.VARCHAR(length=32),
        comment="Verification code (should be hashed)",
        existing_comment="Hashed verification code (SHA-256, 64 hex chars)",
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "email",
        existing_type=sa.VARCHAR(length=255),
        nullable=False,
        comment="Email address",
        existing_comment="Email address (nullable for OAuth users without email)",
    )
    # ### end Alembic commands ###
