"""add auth tables

Revision ID: f579960911db
Revises:
Create Date: 2025-11-26 23:22:33.803864

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "f579960911db"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "oauth_provider_configs",
        sa.Column(
            "provider",
            sa.String(length=20),
            nullable=False,
            comment="OAuth provider type: email, google, github",
        ),
        sa.Column(
            "display_name",
            sa.String(length=100),
            nullable=False,
            comment="Display name for the provider",
        ),
        sa.Column(
            "icon_url",
            sa.String(length=500),
            nullable=True,
            comment="Icon URL for the provider",
        ),
        sa.Column(
            "client_id",
            sa.String(length=255),
            nullable=False,
            comment="OAuth Client ID",
        ),
        sa.Column(
            "client_secret_encrypted",
            sa.String(length=500),
            nullable=False,
            comment="Encrypted OAuth Client Secret",
        ),
        sa.Column(
            "authorization_url",
            sa.String(length=500),
            nullable=True,
            comment="OAuth authorization URL",
        ),
        sa.Column(
            "token_url", sa.String(length=500), nullable=True, comment="OAuth token URL"
        ),
        sa.Column(
            "userinfo_url",
            sa.String(length=500),
            nullable=True,
            comment="OAuth user info URL",
        ),
        sa.Column(
            "default_scopes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
            comment="Default OAuth scopes",
        ),
        sa.Column(
            "config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
            comment="Provider-specific configuration",
        ),
        sa.Column(
            "is_enabled",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
            comment="Whether the provider is enabled",
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("oauth_provider_configs_pkey")),
    )
    op.create_index(
        "idx_oauth_provider_enabled",
        "oauth_provider_configs",
        ["provider", "is_enabled"],
        unique=False,
    )
    op.create_index(
        op.f("oauth_provider_configs_provider_idx"),
        "oauth_provider_configs",
        ["provider"],
        unique=True,
    )
    op.create_table(
        "users",
        sa.Column(
            "uid",
            sa.String(length=16),
            nullable=False,
            comment="External user ID (Base62 encoded Snowflake ID)",
        ),
        sa.Column(
            "username", sa.String(length=50), nullable=False, comment="Unique username"
        ),
        sa.Column(
            "email", sa.String(length=255), nullable=False, comment="Email address"
        ),
        sa.Column(
            "display_name",
            sa.String(length=100),
            nullable=True,
            comment="Display name (can differ from username)",
        ),
        sa.Column(
            "avatar_url",
            sa.String(length=500),
            nullable=True,
            comment="Avatar image URL",
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            server_default="pending",
            nullable=False,
            comment="Account status: pending, active, suspended, deleted",
        ),
        sa.Column(
            "email_verified_at",
            sa.TIMESTAMP(timezone=True),
            nullable=True,
            comment="Email verification timestamp",
        ),
        sa.Column(
            "is_admin",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Whether user has admin privileges",
        ),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
            comment="Extensible user metadata",
        ),
        sa.Column(
            "deleted_at",
            sa.TIMESTAMP(timezone=True),
            nullable=True,
            comment="Soft delete timestamp",
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("users_pkey")),
    )
    op.create_index(
        "idx_users_email_lower",
        "users",
        [sa.literal_column("lower(email)")],
        unique=False,
    )
    op.create_index(
        "idx_users_status_admin", "users", ["status", "is_admin"], unique=False
    )
    op.create_index(op.f("users_email_idx"), "users", ["email"], unique=True)
    op.create_index(op.f("users_is_admin_idx"), "users", ["is_admin"], unique=False)
    op.create_index(op.f("users_status_idx"), "users", ["status"], unique=False)
    op.create_index(op.f("users_uid_idx"), "users", ["uid"], unique=True)
    op.create_index(op.f("users_username_idx"), "users", ["username"], unique=True)
    op.create_table(
        "user_admin_profiles",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "role",
            sa.String(length=20),
            server_default="moderator",
            nullable=False,
            comment="Admin role: super_admin, admin, moderator",
        ),
        sa.Column(
            "permissions",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
            comment="Granular permissions",
        ),
        sa.Column(
            "preferences",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
            comment="Admin UI preferences",
        ),
        sa.Column(
            "last_admin_action_at",
            sa.TIMESTAMP(timezone=True),
            nullable=True,
            comment="Last admin action timestamp",
        ),
        sa.Column(
            "notes", sa.Text(), nullable=True, comment="Internal notes about this admin"
        ),
        sa.Column("granted_by_user_id", sa.Integer(), nullable=True),
        sa.Column(
            "granted_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When admin privileges were granted",
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["granted_by_user_id"],
            ["users.id"],
            name=op.f("user_admin_profiles_granted_by_user_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("user_admin_profiles_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("user_admin_profiles_pkey")),
        sa.UniqueConstraint("user_id", name="uq_admin_profile_user"),
    )
    op.create_index(
        "idx_admin_granted_by",
        "user_admin_profiles",
        ["granted_by_user_id"],
        unique=False,
    )
    op.create_index("idx_admin_role", "user_admin_profiles", ["role"], unique=False)
    op.create_table(
        "user_authentications",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "provider_type",
            sa.String(length=20),
            nullable=False,
            comment="Authentication provider type: email, google, github",
        ),
        sa.Column(
            "provider_user_id",
            sa.String(length=255),
            nullable=False,
            comment="User ID from the provider (email for EMAIL type, OAuth ID for others)",
        ),
        sa.Column(
            "password_hash",
            sa.String(length=255),
            nullable=True,
            comment="Hashed password (only for EMAIL provider)",
        ),
        sa.Column(
            "provider_data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
            comment="OAuth tokens and provider-specific data",
        ),
        sa.Column(
            "is_primary",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Whether this is the primary authentication method",
        ),
        sa.Column(
            "last_used_at",
            sa.TIMESTAMP(timezone=True),
            nullable=True,
            comment="Last time this auth method was used",
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("user_authentications_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("user_authentications_pkey")),
        sa.UniqueConstraint(
            "provider_type", "provider_user_id", name="uq_auth_provider_user"
        ),
    )
    op.create_index(
        "idx_auth_provider_lookup",
        "user_authentications",
        ["provider_type", "provider_user_id"],
        unique=False,
    )
    op.create_index(
        "idx_auth_user_primary",
        "user_authentications",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("is_primary = true"),
    )
    op.create_index(
        op.f("user_authentications_user_id_idx"),
        "user_authentications",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "verification_codes",
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column(
            "email",
            sa.String(length=255),
            nullable=False,
            comment="Target email address",
        ),
        sa.Column(
            "code",
            sa.String(length=32),
            nullable=False,
            comment="Verification code (should be hashed)",
        ),
        sa.Column(
            "purpose",
            sa.String(length=20),
            nullable=False,
            comment="Purpose: registration, login, password_reset, sensitive_op",
        ),
        sa.Column(
            "expires_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            comment="Expiration timestamp",
        ),
        sa.Column(
            "used_at",
            sa.TIMESTAMP(timezone=True),
            nullable=True,
            comment="Timestamp when code was used",
        ),
        sa.Column(
            "attempts",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
            comment="Number of verification attempts",
        ),
        sa.Column(
            "max_attempts",
            sa.Integer(),
            server_default=sa.text("5"),
            nullable=False,
            comment="Maximum allowed attempts",
        ),
        sa.Column(
            "ip_address",
            sa.String(length=45),
            nullable=True,
            comment="IP address that requested the code",
        ),
        sa.Column(
            "user_agent",
            sa.String(length=500),
            nullable=True,
            comment="User agent that requested the code",
        ),
        sa.Column(
            "context",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
            comment="Operation-specific context",
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("verification_codes_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("verification_codes_pkey")),
    )
    op.create_index(
        "idx_vc_active",
        "verification_codes",
        ["email", "purpose"],
        unique=False,
        postgresql_where=sa.text("used_at IS NULL"),
    )
    op.create_index(
        "idx_vc_code_lookup",
        "verification_codes",
        ["code", "purpose", "email"],
        unique=False,
    )
    op.create_index(
        "idx_vc_email_purpose", "verification_codes", ["email", "purpose"], unique=False
    )
    op.create_index(
        op.f("verification_codes_email_idx"),
        "verification_codes",
        ["email"],
        unique=False,
    )
    op.create_index(
        op.f("verification_codes_expires_at_idx"),
        "verification_codes",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("verification_codes_user_id_idx"),
        "verification_codes",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("verification_codes_user_id_idx"), table_name="verification_codes"
    )
    op.drop_index(
        op.f("verification_codes_expires_at_idx"), table_name="verification_codes"
    )
    op.drop_index(op.f("verification_codes_email_idx"), table_name="verification_codes")
    op.drop_index("idx_vc_email_purpose", table_name="verification_codes")
    op.drop_index("idx_vc_code_lookup", table_name="verification_codes")
    op.drop_index(
        "idx_vc_active",
        table_name="verification_codes",
        postgresql_where=sa.text("used_at IS NULL"),
    )
    op.drop_table("verification_codes")
    op.drop_index(
        op.f("user_authentications_user_id_idx"), table_name="user_authentications"
    )
    op.drop_index(
        "idx_auth_user_primary",
        table_name="user_authentications",
        postgresql_where=sa.text("is_primary = true"),
    )
    op.drop_index("idx_auth_provider_lookup", table_name="user_authentications")
    op.drop_table("user_authentications")
    op.drop_index("idx_admin_role", table_name="user_admin_profiles")
    op.drop_index("idx_admin_granted_by", table_name="user_admin_profiles")
    op.drop_table("user_admin_profiles")
    op.drop_index(op.f("users_username_idx"), table_name="users")
    op.drop_index(op.f("users_uid_idx"), table_name="users")
    op.drop_index(op.f("users_status_idx"), table_name="users")
    op.drop_index(op.f("users_is_admin_idx"), table_name="users")
    op.drop_index(op.f("users_email_idx"), table_name="users")
    op.drop_index("idx_users_status_admin", table_name="users")
    op.drop_index("idx_users_email_lower", table_name="users")
    op.drop_table("users")
    op.drop_index(
        op.f("oauth_provider_configs_provider_idx"), table_name="oauth_provider_configs"
    )
    op.drop_index("idx_oauth_provider_enabled", table_name="oauth_provider_configs")
    op.drop_table("oauth_provider_configs")
    # ### end Alembic commands ###
